#!/usr/bin/env bash
# Countdown in seconds
if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
	echo "usage:
	countdown [SECONDS]
	countdown"
	exit 0
fi	
if [ -z $1 ]; then
	#echo -n "Enter number of seconds to countdown from: "
	read -p "Enter number of seconds to countdown from: " seconds
else 
	seconds=$1
fi
x=60
for (( c=1; c<=$seconds; c++ ))
do
	sleep 1
	seconds_remaining=$(( seconds - c ))
	echo -ne "\033[2k\rCountdown: $seconds_remaining seconds"
done
echo -ne "\033[2k\r"
echo "Countdown finished at $(date)"

